# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drowsiness.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drowsiness.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64rowsiness.proto\x12\ndrowsiness\"\x07\n\x05\x45mpty\"L\n\nVideoFrame\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x17\n\x0fsequence_number\x18\x03 \x01(\x05\"\x83\x02\n\x0f\x44\x65tectionResult\x12\x11\n\tis_drowsy\x18\x01 \x01(\x08\x12\x18\n\x10\x64rowsiness_score\x18\x02 \x01(\x02\x12\x1c\n\x14\x65yes_looking_forward\x18\x03 \x01(\x08\x12\x1b\n\x13\x65ye_direction_score\x18\x04 \x01(\x02\x12\x12\n\nhead_angle\x18\x05 \x01(\x02\x12\x13\n\x0b\x61lert_level\x18\x06 \x01(\t\x12\x19\n\x11inference_time_ms\x18\x07 \x01(\x02\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x12\x18\n\x10\x63lient_timestamp\x18\t \x01(\x03\x12\x17\n\x0fsequence_number\x18\n \x01(\x05\"L\n\x0cHealthStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cgrpc_service\x18\x02 \x01(\x08\x12\x16\n\x0e\x61\x63tive_clients\x18\x03 \x01(\x05\x32\xee\x01\n\x13\x44rowsinessDetection\x12I\n\x10\x44\x65tectDrowsiness\x12\x16.drowsiness.VideoFrame\x1a\x1b.drowsiness.DetectionResult\"\x00\x12S\n\x16\x44\x65tectDrowsinessStream\x12\x16.drowsiness.VideoFrame\x1a\x1b.drowsiness.DetectionResult\"\x00(\x01\x30\x01\x12\x37\n\x06Health\x12\x11.drowsiness.Empty\x1a\x18.drowsiness.HealthStatus\"\x00\x42>Z<https://github.com/brshkins/AI_DETECTOR/go-backend/pkg/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drowsiness_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<https://github.com/brshkins/AI_DETECTOR/go-backend/pkg/pb;pb'
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_VIDEOFRAME']._serialized_start=41
  _globals['_VIDEOFRAME']._serialized_end=117
  _globals['_DETECTIONRESULT']._serialized_start=120
  _globals['_DETECTIONRESULT']._serialized_end=379
  _globals['_HEALTHSTATUS']._serialized_start=381
  _globals['_HEALTHSTATUS']._serialized_end=457
  _globals['_DROWSINESSDETECTION']._serialized_start=460
  _globals['_DROWSINESSDETECTION']._serialized_end=698
# @@protoc_insertion_point(module_scope)
